"""RobotTwin — parametric geometry for the parallel-jaw gripper (v2, servo).

Pure Python, importable anywhere (no Fusion dependency): this module IS the
parametric layer, in the same architecture as
engineering/fusion/robot_linkages/linkage_geometry.py (whose primitive
classes and shared interface constants it imports). It defines every
dimension, derives the drive-train stations, emits each part as an ordered
list of primitive booleans, and self-checks every mating clearance
analytically.

Consumers:
    gripper.py                 Fusion wrapper: replays the primitive lists
                               through TemporaryBRepManager and exports.
    gripper_parameters.yaml    the design parameters (this module only holds
                               purchased-hardware dimensions and derivations).

Local frame: x = 0 is the TCP plane (the forearm tip plate's outer face),
+X points away from the arm along the tool axis, Y is the jaw-travel axis,
Z is "up" (lid side). In the arm's world frame at the reference pose this
frame sits at (l_upper + l_fore, 0, shoulder_z) with the same orientation.

Architecture (SG-90 servo + rack-and-pinion; replaces the v1 NEMA 8 +
rotating-lead-screw drive — see README.md):

  An SG-90 micro servo is bench-screwed nose-first to a printed BULKHEAD
  PLATE (its two mounting-tab self-tappers), output shaft on the tool axis
  pointing +X. The plate slides down vertical grooves in the housing side
  walls and is captured by the lid — the whole servo cartridge drops in
  from the top, no fasteners into the housing.

  The PINION is a printed lantern gear: a flange pressed onto the servo's
  21T spline (Ø4.5 bore over the Ø4.8 spline broaches on assembly; the
  servo's own horn screw retains it) carrying eight Ø4.5 pins on a Ø18
  pitch circle. Two RACKS — integrated into the jaw sliders, one above and
  one below the pinion — carry trochoidal tooth spaces generated by
  simulated hobbing: the pin-radius cutter is subtracted along the cycloid
  the pin centers trace in each rack's frame (the same construction the
  cycloidal gearbox generator uses for its discs). Pin gearing is exact
  conjugate action with no undercut at this tooth count, and every tooth
  is a vertical-walled prism the printer handles cleanly.

  Opposite rack velocities give symmetric jaw motion: 18 mm of rack travel
  per jaw (~115 degrees of servo rotation) opens the jaws 0-36 mm. The
  servo is its own absolute position reference, so v1's homing microswitch
  is gone. NOT self-locking: grip needs the servo powered (README).

  Mounting contract (unchanged from v1 — the printed forearm is NOT
  touched): the back plate bolts with 4 x M3 x 8 on the Ø16 BCD into the
  forearm tip plate's outer-face inserts; a Ø10.3 pilot boss registers in
  the plate's Ø10.5 bore and passes the servo lead out through its Ø7
  center hole to the plate's bottom-edge wire notch.
"""

import math
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, '..', 'fusion', 'robot_linkages'))
from linkage_geometry import (                                   # noqa: E402
    Box, Cyl, Part, Checks,
    M3_CLEAR_D, M3_CB_D, M3_HEAD_D, M3_HEAD_H,
    INSERT_D, INSERT_POCKET, T8_BCD, T8_BORE_D,
    FA_PLATE_T, FA_PLATE_HALF, BUILD_VOLUME,
)


# ---------------------------------------------------------------------------
# Purchased hardware (fixed properties of the parts; design parameters live
# in gripper_parameters.yaml)
# ---------------------------------------------------------------------------

# SG-90 9 g micro servo (TowerPro and clones). Long case dimension is
# mounted along Z (nose up during the drop-in, shaft along +X in service).
# Clone envelopes vary ~±0.3 mm; the pockets carry clearance for that.
SG90_L = 22.8                   # case length (along Z here)
SG90_W = 12.4                   # case width (along Y)
SG90_SHAFT_OFF = 5.9            # shaft axis from the gearhead end of the case
SG90_NOSE = 4.0                 # mounting-tab face -> case top (through the plate)
SG90_BEHIND_TAB = 19.2          # mounting-tab face -> case back (incl. the tab)
SG90_TAB_L = 4.7                # each tab beyond the case end
SG90_TAB_T = 2.5
SG90_HOLE_OFF = 2.4             # tab hole center beyond the case end
SG90_SPLINE_D = 4.8             # 21T output spline
SG90_SPLINE_H = 4.0
SG90_STALL_NM = 0.176           # 1.8 kg*cm at 4.8 V
SG90_MASS_G = 10.5              # with lead
SG90_TAP_D = 1.8                # pilot holes for the tab self-tappers

SPLINE_SCREW_L = 8.0            # the servo's own horn screw (~M2 x 8)
SPLINE_SCREW_CLEAR = 2.5
SPLINE_SCREW_HEAD_D = 4.0

PETG_DENSITY = 1.27e-3          # g/mm^3
PRINT_FILL = 0.55               # effective density factor (walls + 30 % infill)

HOB_STEP_RAD = 0.04             # cam-angle step of the rack hobbing sweep
HOB_PHI_MAX = 1.0               # pin engagement half-angle swept per tooth
HOB_MARGIN_RAD = 0.35           # hob overtravel beyond the jaw stroke


# ---------------------------------------------------------------------------
# Parameters — gripper_parameters.yaml is the only source.
# Same minimal 'Section: / key: number' parser as the gearbox generator.
# ---------------------------------------------------------------------------

def yaml_path():
    return os.path.join(_HERE, 'gripper_parameters.yaml')


def read_params():
    with open(yaml_path(), 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()
    data, section = {}, None
    for ln in lines:
        ln = ln.split('#', 1)[0].rstrip()
        if not ln.strip():
            continue
        m = re.match(r'^(\S[^:]*):\s*$', ln)
        if m:
            section = m.group(1).strip()
            data[section] = {}
            continue
        m = re.match(r'^\s+([A-Za-z_][\w]*)\s*:\s*([-0-9.]+)\s*$', ln)
        if m and section:
            data[section][m.group(1)] = float(m.group(2))
    return data


# ---------------------------------------------------------------------------
# Derived stations. Everything hangs off this dict; builders and checks
# share it so a parameter change propagates everywhere.
# ---------------------------------------------------------------------------

def stations(p):
    d, j, b = p['drive'], p['jaws'], p['body']
    st = {}
    st['clr'] = b['slide_clearance']
    st['gap'] = b['running_gap']

    # -- pin gearing --
    st['n_pins'] = int(d['pin_count'])
    st['r'] = d['pitch_radius']                      # pitch radius = jaw lever
    st['pin_r'] = d['pin_d'] / 2.0
    st['cutter_r'] = st['pin_r'] + d['profile_clearance']
    st['travel'] = j['max_opening'] / 2.0            # stroke per jaw
    st['rot'] = st['travel'] / st['r']               # servo swing, rad
    st['rot_deg'] = math.degrees(st['rot'])
    st['pitch'] = 2 * math.pi * st['r'] / st['n_pins']

    # -- axial stations, back plate to fingertip --
    st['back_t'] = b['back_thickness']
    st['boss_l'] = 4.0                               # pilot boss into the plate bore
    st['boss_d'] = T8_BORE_D - 0.2
    st['wire_d'] = 7.0
    st['bay0'] = st['back_t'] + 1.0                  # mount heads live in the gap
    st['case_back'] = st['back_t'] + 3.0
    st['bp0'] = st['case_back'] + SG90_BEHIND_TAB    # bulkhead plate, back face
    st['bp_t'] = 3.4                                 # < SG90_NOSE: tabs clamp it
    st['bp1'] = st['bp0'] + st['bp_t']
    st['case_top'] = st['bp0'] + SG90_NOSE           # 0.6 proud of the plate
    st['spline_x1'] = st['case_top'] + SG90_SPLINE_H
    st['flange_x0'] = st['bp1'] + 1.0
    st['flange_t'] = 3.0
    st['flange_x1'] = st['flange_x0'] + st['flange_t']
    st['flange_d'] = 2 * (st['r'] + st['pin_r'])     # pins tangent to the rim
    st['pin_x0'] = st['flange_x1']
    st['pin_x1'] = st['pin_x0'] + d['pin_length']
    st['rx0'] = st['pin_x0'] + 0.5                   # rack tooth band (inside pins)
    st['rx1'] = st['pin_x1'] - 0.5
    st['riser_x0'] = st['pin_x1'] + 0.5
    st['riser_x1'] = st['riser_x0'] + 3.9
    st['jb0'] = st['pin_x1'] + 1.4                   # jaw head block
    st['cav_x1'] = st['jb0'] + 9.0                   # carrier tunnel front
    st['fp1'] = st['cav_x1'] + 3.0                   # face plate = housing front
    st['finger_x1'] = st['fp1'] + j['finger_length']
    st['extent'] = st['finger_x1']                   # reach beyond the TCP

    # -- rack tooth geometry (mirrored bands above/below the pinion) --
    st['tip_z'] = st['r'] - 2.3                      # tooth tip plane (addendum)
    st['core_r'] = st['tip_z'] - 1.0                 # pinion core clears the tips
    st['root_z'] = st['r'] + st['cutter_r']          # deepest hob reach
    st['bar_back'] = st['root_z'] + 4.5              # solid backing behind roots

    # -- housing cross-section --
    st['out_hw'] = FA_PLATE_HALF
    st['int_hw'] = st['out_hw'] - b['wall']
    st['head_hw'] = 28.0
    st['floor_z1'] = -st['bar_back'] - st['gap']     # lower rack rides the floor
    st['floor_z0'] = st['floor_z1'] - 3.5
    st['roof_z'] = 22.0                              # wall tops / lid seat
    st['lid_z1'] = st['roof_z'] + 3.0
    st['win_x0'] = st['rx0'] - 0.2                   # walls end; bars sweep here
    st['rib_x0'] = st['rx0'] - 0.1                   # lid rib backs the upper rack
    st['rib_x1'] = st['riser_x0'] - 0.8
    st['rib_z0'] = st['bar_back'] + st['gap']
    st['tun_z0'], st['tun_z1'] = -11.35, 3.35        # carrier tunnel
    st['head_top'] = 6.0
    st['fp_slot_hz'] = 4.0                           # face-plate slot half height

    # -- bulkhead plate (servo cartridge) --
    st['bp_hw'] = st['int_hw'] + 1.8                 # engages 1.8 into each groove
    st['groove_hw'] = st['int_hw'] + 2.0
    st['bp_z0'] = st['floor_z1'] + 0.1
    st['bp_z1'] = st['roof_z'] - 0.2                 # lid captures the top edge
    st['win_hw'] = SG90_W / 2 + 0.3                  # nose window in the plate
    st['win_z0'] = -SG90_SHAFT_OFF - 0.3
    st['win_z1'] = SG90_L - SG90_SHAFT_OFF + 0.3
    st['tab_z_lo'] = -(SG90_SHAFT_OFF + SG90_HOLE_OFF)
    st['tab_z_hi'] = SG90_L - SG90_SHAFT_OFF + SG90_HOLE_OFF
    st['tab_tip_lo'] = -SG90_SHAFT_OFF - SG90_TAB_L
    st['tab_tip_hi'] = SG90_L - SG90_SHAFT_OFF + SG90_TAB_L

    # -- jaw sliders (modeled at the OPEN pose) --
    st['jaw_open_off'] = st['travel']
    st['fin_y0_closed'] = j['pad_proud']             # pads meet at y = 0
    st['car_y0'] = st['fin_y0_closed'] + st['travel']
    st['car_len'] = j['carrier_length']
    st['car_x0'], st['car_x1'] = st['jb0'] + 0.5, st['cav_x1'] - 0.5
    st['fin_t'] = j['finger_thickness']
    st['fin_h'] = j['finger_height']
    st['pad_t'] = j['pad_thickness']
    st['pad_proud'] = j['pad_proud']
    st['riser_y0_rel'] = 11.0                        # riser band on the carrier
    st['riser_y1_rel'] = 17.0
    st['bar_tip_y'] = -9.0                           # inner end of the rack bar
    # outermost hob reach — teeth must end before the riser
    st['hob_y_max'] = (st['r'] * math.sin(HOB_PHI_MAX)
                      + st['r'] * (st['rot'] + HOB_MARGIN_RAD))

    # -- performance --
    eff = d['mesh_efficiency']
    st['f_jaw'] = d['servo_torque_nm'] * eff / (2 * st['r'] / 1000.0)
    st['f_jaw_stall'] = SG90_STALL_NM * eff / (2 * st['r'] / 1000.0)
    # cantilevered pin root bending at stall, worst single-pin contact
    pin_arm = (st['rx0'] + st['rx1']) / 2 - st['pin_x0']
    st['pin_sigma'] = (st['f_jaw_stall'] * pin_arm * 32.0
                      / (math.pi * (2 * st['pin_r']) ** 3))
    st['servo_travel_deg'] = d['servo_travel_deg']
    return st


# ---------------------------------------------------------------------------
# Rack hobbing — pin-cutter sweep in each rack's frame (cycloid), the same
# construction the cycloidal gearbox uses for its disc profiles.
# ---------------------------------------------------------------------------

def rack_cutters(st, s):
    """Cutter centers (y, z) for the rack on side s (+1 above the pinion,
    -1 below), in the jaw's OPEN-pose frame. Rolling contact: rotation by
    theta about +X (positive = closing) puts a pin of phase alpha at
    (-r sin(alpha+theta), r cos(alpha+theta)); the s=+1 rack translates
    -r*theta and the s=-1 rack +r*theta. Mapping the pin into the rack's
    open frame and sampling theta over the stroke (plus margin) traces the
    cycloid whose envelope is the conjugate tooth space — note d(y)/d(theta)
    vanishes at the cusp (pure rolling), which is what leaves the flanks
    standing next to each pocket."""
    r, n = st['r'], st['n_pins']
    phi0 = 0.0 if s > 0 else math.pi                 # engagement direction
    z_keep = st['tip_z'] - st['cutter_r'] - 0.5      # cutter must reach the bar
    out = []
    for jdx in range(-3, n + 4):
        alpha = 2 * math.pi * jdx / n
        t0 = max(-HOB_MARGIN_RAD, phi0 - HOB_PHI_MAX - alpha)
        t1 = min(st['rot'] + HOB_MARGIN_RAD, phi0 + HOB_PHI_MAX - alpha)
        if t1 <= t0:
            continue
        k = 0
        while True:
            th = t0 + k * HOB_STEP_RAD
            if th > t1:
                break
            k += 1
            phi = alpha + th
            y = -r * math.sin(phi) + s * r * th
            z = r * math.cos(phi)
            if s > 0 and z > z_keep:
                out.append((y, z))
            elif s < 0 and z < -z_keep:
                out.append((y, z))
    return out


def mesh_contact_gaps(st, poses=61, h=0.08):
    """Numeric drive-continuity audit: rasterize the hobbed tooth band and
    count stroke poses where NO pin bears on a flank in the closing (+y
    normal) or opening (-y) direction. Both counts must be zero — pin
    gearing has no analytic contact-ratio shortcut worth trusting here.
    Symmetric racks: auditing the s=+1 side covers both."""
    r, n = st['r'], st['n_pins']
    cr, pr = st['cutter_r'], st['pin_r']
    y0g, y1g = -14.0, 32.0
    z0g, z1g = st['tip_z'], st['root_z'] + 0.2
    ny, nz = int((y1g - y0g) / h), int((z1g - z0g) / h)
    solid = [[True] * nz for _ in range(ny)]
    for (cy, cz) in rack_cutters(st, +1):
        iy0 = max(0, int((cy - cr - y0g) / h))
        iy1 = min(ny, int((cy + cr - y0g) / h) + 1)
        for iy in range(iy0, iy1):
            dy2 = cr * cr - (y0g + iy * h - cy) ** 2
            if dy2 <= 0:
                continue
            dz = math.sqrt(dy2)
            for iz in range(max(0, int((cz - dz - z0g) / h)),
                            min(nz, int((cz + dz - z0g) / h) + 1)):
                solid[iy][iz] = False
    bad_close = bad_open = 0
    for i in range(poses):
        th = st['rot'] * i / (poses - 1)
        plus = minus = False
        for k in range(-2, n + 3):
            phi = 2 * math.pi * k / n + th
            py = -r * math.sin(phi) + r * th
            pz = r * math.cos(phi)
            if pz < st['tip_z'] - pr - 0.3:
                continue
            for iy in range(max(0, int((py - cr - 0.3 - y0g) / h)),
                            min(ny, int((py + cr + 0.3 - y0g) / h) + 1)):
                for iz in range(nz):
                    if not solid[iy][iz]:
                        continue
                    dy = y0g + iy * h - py
                    dz = z0g + iz * h - pz
                    dist = math.hypot(dy, dz)
                    if abs(dist - cr) < 1.6 * h:
                        if dy / dist > 0.25:
                            plus = True
                        if dy / dist < -0.25:
                            minus = True
            if plus and minus:
                break
        bad_close += 0 if plus else 1
        bad_open += 0 if minus else 1
    return bad_close, bad_open


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def _bcd45(r=T8_BCD / 2):
    c = r * math.cos(math.radians(45))
    return [(c, c), (c, -c), (-c, c), (-c, -c)]


def _lid_screw_xy(st):
    return [(12.0, 18.0), (12.0, -18.0), (30.0, 18.0), (30.0, -18.0),
            (st['fp1'] - 1.5, 14.0), (st['fp1'] - 1.5, -14.0)]


def build_body(st):
    """Housing: back plate with the pilot boss, floor, side walls with the
    bulkhead-plate grooves, jaw head with the carrier tunnel and face plate.
    The walls stop at the rack window (the bars sweep through free air
    there); the lid's rib and the floor are the rack back-up rails. The
    servo cartridge and the pinion drop in from the open top."""
    p = Part('rt_grip_body')
    ihw, ohw = st['int_hw'], st['out_hw']
    p.add(Box(0, st['back_t'], -ohw, ohw, -ohw, ohw))            # back plate
    p.add(Cyl((-st['boss_l'], 0, 0), (0.05, 0, 0), st['boss_d']))  # pilot boss
    p.add(Box(st['back_t'], st['fp1'], -ohw, ohw,
              st['floor_z0'], st['floor_z1']))                   # floor
    for s in (+1, -1):
        p.add(Box(st['back_t'], st['win_x0'], s * ihw, s * ohw,
                  st['floor_z1'], st['roof_z']))                 # side walls
    p.add(Box(st['jb0'], st['fp1'], -st['head_hw'], st['head_hw'],
              st['floor_z1'], st['head_top']))                   # jaw head
    p.add(Box(st['cav_x1'], st['fp1'], -st['head_hw'], st['head_hw'],
              st['floor_z1'], st['head_top'] + 2.0))             # face plate low
    p.add(Box(st['cav_x1'], st['fp1'], -ohw, ohw,
              st['head_top'] + 2.0, st['roof_z']))               # face plate up
    # --- cuts ---
    for y, z in _bcd45():                                        # mounting
        p.cut(Cyl((-1, y, z), (st['back_t'] + 0.1, y, z), M3_CLEAR_D))
        p.cut(Cyl((2.0, y, z), (st['back_t'] + 0.1, y, z), M3_CB_D))
    p.cut(Cyl((-st['boss_l'] - 0.2, 0, 0), (st['back_t'] + 0.1, 0, 0),
              st['wire_d']))                                     # servo lead
    for s in (+1, -1):                               # bulkhead plate grooves
        p.cut(Box(st['bp0'] - 0.2, st['bp1'] + 0.2, s * (ihw - 0.1),
                  s * st['groove_hw'], st['floor_z1'] - 0.1, st['roof_z'] + 0.1))
    # jaw head: carrier tunnel, face-plate slot, riser passages (top and
    # bottom — each rack's riser crosses the head band on its own level)
    p.cut(Box(st['jb0'], st['cav_x1'], -st['head_hw'] - 1, st['head_hw'] + 1,
              st['tun_z0'], st['tun_z1']))
    p.cut(Box(st['cav_x1'] - 0.1, st['fp1'] + 0.1, -st['head_hw'] - 1,
              st['head_hw'] + 1, -st['fp_slot_hz'], st['fp_slot_hz']))
    p.cut(Box(st['riser_x0'] - 0.2, st['riser_x1'] + 0.2, -st['head_hw'] - 1,
              st['head_hw'] + 1, st['tun_z1'] - 0.2, st['head_top'] + 0.1))
    p.cut(Box(st['riser_x0'] - 0.2, st['riser_x1'] + 0.2, -st['head_hw'] - 1,
              st['head_hw'] + 1, st['floor_z1'] + 0.1, st['tun_z0'] + 0.2))
    for x, y in _lid_screw_xy(st):                   # lid insert pockets
        p.cut(Cyl((x, y, st['roof_z'] - INSERT_POCKET),
                  (x, y, st['roof_z'] + 0.1), INSERT_D))
    return p


def build_lid(st):
    """Flat top plate, 6 x M3 into the body's insert pockets. A hanging rib
    over the rack window is the upper rack's back-up rail (it cannot live on
    the body: the servo cartridge and pinion drop in through that volume)."""
    p = Part('rt_grip_lid')
    p.add(Box(st['back_t'] + 1.0, st['fp1'], -st['out_hw'], st['out_hw'],
              st['roof_z'], st['lid_z1']))
    p.add(Box(st['rib_x0'], st['rib_x1'], -st['int_hw'], st['int_hw'],
              st['rib_z0'], st['roof_z'] + 0.5))
    for x, y in _lid_screw_xy(st):
        p.cut(Cyl((x, y, st['roof_z'] - 0.1), (x, y, st['lid_z1'] + 0.1),
                  M3_CLEAR_D))
        p.cut(Cyl((x, y, st['lid_z1'] - M3_HEAD_H), (x, y, st['lid_z1'] + 0.1),
                  M3_CB_D))
    return p


def build_bulkhead(st):
    """Servo cartridge plate: the SG-90 nose passes the center window, the
    two mounting-tab self-tappers bite the printed pilot holes above and
    below it. The loaded plate slides down the wall grooves and the lid
    captures its top edge. Grip reaction torque goes tab -> plate -> walls."""
    p = Part('rt_grip_bulkhead')
    p.add(Box(st['bp0'], st['bp1'], -st['bp_hw'], st['bp_hw'],
              st['bp_z0'], st['bp_z1']))
    p.cut(Box(st['bp0'] - 0.1, st['bp1'] + 0.1, -st['win_hw'], st['win_hw'],
              st['win_z0'], st['win_z1']))
    for z in (st['tab_z_lo'], st['tab_z_hi']):
        p.cut(Cyl((st['bp0'] - 0.1, 0, z), (st['bp1'] + 0.1, 0, z), SG90_TAP_D))
    return p


def build_pinion(st):
    """Lantern pinion: flange + core pressed onto the servo spline (Ø4.5
    bore broaches over the Ø4.8 21T spline), retained by the servo's horn
    screw down the core's center bore. Eight cantilevered pins are the
    teeth; both racks mesh the same pin cage 180 degrees apart. Prints
    flange-down, pins vertical, no supports."""
    p = Part('rt_grip_pinion')
    p.add(Cyl((st['flange_x0'], 0, 0), (st['flange_x1'], 0, 0), st['flange_d']))
    p.add(Cyl((st['flange_x0'], 0, 0), (st['pin_x1'], 0, 0), 2 * st['core_r']))
    for k in range(st['n_pins']):
        a = 2 * math.pi * k / st['n_pins']
        y, z = st['r'] * math.sin(a), st['r'] * math.cos(a)
        p.add(Cyl((st['flange_x1'] - 0.6, y, z), (st['pin_x1'], y, z),
                  2 * st['pin_r']))
    p.cut(Cyl((st['flange_x0'] - 0.1, 0, 0), (st['spline_x1'] + 0.2, 0, 0),
              SG90_SPLINE_D - 0.3))
    p.cut(Cyl((st['spline_x1'], 0, 0), (st['pin_x1'] + 0.1, 0, 0),
              SPLINE_SCREW_CLEAR))
    p.cut(Cyl((st['pin_x1'] - 1.5, 0, 0), (st['pin_x1'] + 0.1, 0, 0),
              SPLINE_SCREW_HEAD_D + 1.0))
    return p


def build_jaw(st, s):
    """One jaw slider, modeled at the OPEN pose: transverse carrier in the
    head tunnel, neck through the face-plate slot, finger with the TPU pad
    pocket, and the rack: a toothed bar in the window band (above the
    pinion for s = +1, below for s = -1), an outer arm past the pin cage,
    and a riser through its head passage down/up to the carrier."""
    name = 'rt_grip_jaw_p' if s > 0 else 'rt_grip_jaw_n'
    p = Part(name)
    fy0 = st['car_y0']                               # finger inner face (open)
    car_y1 = fy0 + st['car_len']
    ry0, ry1 = fy0 + st['riser_y0_rel'], fy0 + st['riser_y1_rel']
    if s > 0:
        bar_z = (st['tip_z'], st['bar_back'])
        riser_z = (st['tun_z1'] - st['clr'] - 0.2, st['bar_back'])
    else:
        bar_z = (-st['bar_back'], -st['tip_z'])
        riser_z = (-st['bar_back'], st['tun_z0'] + st['clr'] + 1.0)
    p.add(Box(st['rx0'], st['rx1'], s * st['bar_tip_y'], s * ry1,
              bar_z[0], bar_z[1]))                   # toothed bar
    p.add(Box(st['rx1'] - 0.5, st['riser_x1'], s * ry0, s * ry1,
              bar_z[0], bar_z[1]))                   # outer arm past the pins
    p.add(Box(st['riser_x0'], st['riser_x1'], s * ry0, s * ry1,
              riser_z[0], riser_z[1]))               # riser to the carrier
    p.add(Box(st['car_x0'], st['car_x1'], s * fy0, s * car_y1,
              st['tun_z0'] + st['clr'], st['tun_z1'] - st['clr']))
    p.add(Box(st['car_x1'] - 0.1, st['fp1'], s * fy0, s * (fy0 + st['fin_t'] + 3),
              -st['fp_slot_hz'] + st['clr'], st['fp_slot_hz'] - st['clr']))
    p.add(Box(st['fp1'], st['finger_x1'], s * fy0, s * (fy0 + st['fin_t']),
              st['tun_z0'] + st['clr'], st['tun_z0'] + st['clr'] + st['fin_h']))
    # pad pocket, 1 mm deep, on the gripping face
    p.cut(Box(st['fp1'] + 3, st['finger_x1'] - 1, s * (fy0 - 0.1), s * (fy0 + 1.0),
              st['tun_z0'] + 2, st['tun_z0'] + st['fin_h'] - 1))
    # hob the tooth spaces
    for y, z in rack_cutters(st, s):
        p.cut(Cyl((st['rx0'] - 0.15, y, z), (st['rx1'] + 0.15, y, z),
                  2 * st['cutter_r']))
    return p


def build_pad(st):
    """TPU pad (print 2): drops into the finger pocket, 1 mm keyed + proud."""
    p = Part('rt_grip_pad')
    p.add(Box(0, st['finger_x1'] - st['fp1'] - 4, 0,
              st['pad_t'], 0, st['fin_h'] - 3))
    return p


# ---------------------------------------------------------------------------
# Hardware solids (audit / assembly visualization only)
# ---------------------------------------------------------------------------

def servo_solid(st):
    p = Part('hw_servo')
    p.add(Box(st['case_back'], st['case_top'], -SG90_W / 2, SG90_W / 2,
              -SG90_SHAFT_OFF, SG90_L - SG90_SHAFT_OFF))
    for z0, z1 in ((st['tab_tip_lo'], -SG90_SHAFT_OFF),
                   (SG90_L - SG90_SHAFT_OFF, st['tab_tip_hi'])):
        p.add(Box(st['bp0'] - SG90_TAB_T, st['bp0'], -SG90_W / 2, SG90_W / 2,
                  z0, z1))
    p.add(Cyl((st['case_top'], 0, 0), (st['spline_x1'], 0, 0), SG90_SPLINE_D))
    return p


# ---------------------------------------------------------------------------
# Design assembly + analytic verification
# ---------------------------------------------------------------------------

def design():
    p = read_params()
    st = stations(p)
    parts = {
        'rt_grip_body': build_body(st),
        'rt_grip_lid': build_lid(st),
        'rt_grip_bulkhead': build_bulkhead(st),
        'rt_grip_pinion': build_pinion(st),
        'rt_grip_jaw_p': build_jaw(st, +1),
        'rt_grip_jaw_n': build_jaw(st, -1),
        'rt_grip_pad': build_pad(st),
    }
    hardware = {
        'hw_servo': servo_solid(st),
    }

    c = Checks()
    # --- mounting (frozen forearm interface) ---
    c.ck('mount screw engagement in plate insert (M3x8)',
         8.0 - (st['back_t'] - 2.0), 4.5)
    bolt_r = T8_BCD / 2 + M3_CB_D / 2
    c.ck('mount counterbores inside the back plate', st['out_hw'] - bolt_r, 3.0)
    c.ck('mount counterbores clear the wire bore',
         T8_BCD / 2 - M3_CB_D / 2 - st['wire_d'] / 2, 0.5)
    c.ck('mount heads sunk below the bay', st['back_t'] - 2.0 - M3_HEAD_H, 0.0)
    c.ck('pilot boss fits the plate bore', T8_BORE_D - st['boss_d'], 0.15)
    c.ck('pilot boss shorter than the plate', FA_PLATE_T - st['boss_l'], 2.0)
    c.ck('wire bore wall inside the boss',
         (st['boss_d'] - st['wire_d']) / 2, 1.2)
    c.ck('mount holes clear the pilot boss',
         T8_BCD / 2 - M3_CLEAR_D / 2 - st['boss_d'] / 2, 0.5)
    # --- servo bay + bulkhead plate ---
    c.ck('servo case clears the back plate', st['case_back'] - st['back_t'], 1.0)
    c.ck('servo width vs the interior', st['int_hw'] - SG90_W / 2, 1.0)
    c.ck('nose window clears the case (width)', st['win_hw'] - SG90_W / 2, 0.25)
    c.ck('nose window clears the case (top)',
         st['win_z1'] - (SG90_L - SG90_SHAFT_OFF), 0.25)
    c.ck('nose window clears the case (bottom)',
         -SG90_SHAFT_OFF - st['win_z0'], 0.25)
    c.ck('nose proud of the plate front', st['case_top'] - st['bp1'], 0.3)
    c.ck('tabs clamp the plate (thickness fit)', SG90_NOSE - st['bp_t'], 0.4)
    c.ck('upper tab hole in solid plate (to window)',
         st['tab_z_hi'] - SG90_TAP_D / 2 - st['win_z1'], 0.8)
    c.ck('upper tab hole in solid plate (to edge)',
         st['bp_z1'] - st['tab_z_hi'] - SG90_TAP_D / 2, 0.8)
    c.ck('lower tab hole in solid plate (to window)',
         st['win_z0'] - st['tab_z_lo'] - SG90_TAP_D / 2, 0.8)
    c.ck('lower tab hole in solid plate (to edge)',
         st['tab_z_lo'] - SG90_TAP_D / 2 - st['bp_z0'], 0.8)
    c.ck('upper tab tip under the roof', st['roof_z'] - st['tab_tip_hi'], 0.2)
    c.ck('lower tab tip above the floor', st['tab_tip_lo'] - st['floor_z1'], 0.5)
    c.ck('plate groove engagement', st['bp_hw'] - st['int_hw'], 1.2)
    c.ck('plate slides in the groove', st['groove_hw'] - st['bp_hw'], 0.1)
    c.ck('plate top captured by the lid', st['roof_z'] - st['bp_z1'], 0.1)
    c.ck('plate capture gap not sloppy', 0.5 - (st['roof_z'] - st['bp_z1']), 0.0)
    # --- pinion ---
    c.ck('spline engagement in the pinion bore',
         min(st['spline_x1'], st['flange_x1']) - st['flange_x0'], 2.5)
    c.ck('horn screw engages the spline thread',
         st['spline_x1'] - (st['pin_x1'] - 1.5 - SPLINE_SCREW_L), 2.0)
    c.ck('horn screw head wall in the core',
         st['core_r'] - (SPLINE_SCREW_HEAD_D + 1.0) / 2, 1.5)
    c.ck('pinion flange clears the bulkhead plate',
         st['flange_x0'] - st['bp1'], 0.5)
    c.ck('pinion flange clears the servo nose',
         st['flange_x0'] - st['case_top'], 0.3)
    c.ck('pinion core clears the rack tips', st['tip_z'] - st['core_r'], 0.6)
    c.ck('pins tangent inside the flange rim',
         st['flange_d'] / 2 - (st['r'] + st['pin_r']), 0.0)
    c.ck('pin root bending margin at stall (MPa)',
         20.0 - st['pin_sigma'], 10.0)
    c.ck('drop-in: pinion clears the interior walls',
         st['int_hw'] - (st['r'] + st['pin_r']), 1.0)
    # --- racks + rails ---
    c.ck('servo swing within usable travel (deg)',
         st['servo_travel_deg'] - st['rot_deg'], 15.0)
    c.ck('rack band inside the pin length (back)', st['rx0'] - st['pin_x0'], 0.3)
    c.ck('rack band inside the pin length (front)', st['pin_x1'] - st['rx1'], 0.3)
    c.ck('rack backing behind the tooth roots',
         st['bar_back'] - st['root_z'], 3.0)
    c.ck('hob covers the bar tip', -st['bar_tip_y']
         - st['r'] * math.sin(HOB_PHI_MAX), 0.0)
    c.ck('teeth end before the riser',
         st['fin_y0_closed'] + st['riser_y0_rel'] + st['travel']
         - st['hob_y_max'], 1.0)
    c.ck('hob step fine enough (arc mm)', 0.5 - st['r'] * HOB_STEP_RAD, 0.0)
    c.ck('upper rack running gap to the lid rib',
         st['rib_z0'] - st['bar_back'], 0.2)
    c.ck('upper rail gap not sloppy', 0.8 - (st['rib_z0'] - st['bar_back']), 0.0)
    c.ck('lower rack running gap to the floor',
         -st['bar_back'] - st['floor_z1'], 0.2)
    c.ck('lower rail gap not sloppy',
         0.8 - (-st['bar_back'] - st['floor_z1']), 0.0)
    c.ck('lid rib clears the risers', st['riser_x0'] - st['rib_x1'], 0.4)
    c.ck('lid rib above the pin sweep',
         st['rib_z0'] - (st['r'] + st['pin_r']), 1.0)
    c.ck('lid rib clears the wall tops', st['rib_x0'] - st['win_x0'], 0.0)
    c.ck('rack bars clear the bulkhead plate', st['rx0'] - st['bp1'], 1.0)
    c.ck('rack bars clear the pinion flange', st['rx0'] - st['flange_x1'], 0.3)
    c.ck('rack bars clear each other', 2 * st['tip_z'], 2.0)
    c.ck('riser clears the pin sweep (lateral, closed)',
         st['fin_y0_closed'] + st['riser_y0_rel'] - (st['r'] + st['pin_r']), 1.0)
    c.ck('riser clears the pins (axial)', st['riser_x0'] - st['pin_x1'], 0.4)
    c.ck('riser band inside the carrier',
         st['car_len'] - st['riser_y1_rel'], 2.0)
    # --- jaws + head ---
    c.ck('carrier engaged in tunnel at OPEN',
         st['head_hw'] - st['car_y0'], 7.0)
    c.ck('carriers clear each other at CLOSED', 2 * st['fin_y0_closed'], 1.0)
    c.ck('head roof band above the tunnel', st['head_top'] - st['tun_z1'], 2.0)
    c.ck('head ring intact behind the riser passages',
         st['cav_x1'] - (st['riser_x1'] + 0.2), 3.0)
    c.ck('riser passages clear the pin cage', st['jb0'] - st['pin_x1'], 1.0)
    c.ck('face-plate slot admits the neck',
         st['fp_slot_hz'] - st['clr'] - 3.0, 0.0)
    c.ck('fingers meet at closed (opening = spec)',
         2 * (st['jaw_open_off'] + st['fin_y0_closed'] - st['pad_proud'])
         - 2 * st['travel'], 0.0)
    c.ck('working grip force (N)', st['f_jaw'], 4.0)
    bad_close, bad_open = mesh_contact_gaps(st)
    c.ck('mesh bears closing at every stroke pose', -bad_close, 0.0)
    c.ck('mesh bears opening at every stroke pose', -bad_open, 0.0)
    # --- printability ---
    c.ck('pin aspect ratio printable (len/dia)',
         2.5 - (st['pin_x1'] - st['pin_x0']) / (2 * st['pin_r']), 0.0)
    for name, part in parts.items():
        lo, hi = part.bbox()
        dims = [hi[i] - lo[i] for i in range(3)]
        c.ck(f'{name} fits build volume', BUILD_VOLUME - max(dims), 5.0)

    return {'parts': parts, 'hardware': hardware, 'checks': c, 'st': st,
            'params': p}


def grid_volume_mm3(part, step=2.0):
    """Coarse voxel volume for the mass budget (±10-15 %)."""
    lo, hi = part.bbox()
    n = 0
    x = lo[0] + step / 2
    while x < hi[0]:
        y = lo[1] + step / 2
        while y < hi[1]:
            z = lo[2] + step / 2
            while z < hi[2]:
                if part.contains((x, y, z)):
                    n += 1
                z += step
            y += step
        x += step
    return n * step ** 3


def mass_estimate(d):
    """Printed parts via voxel volume + purchased hardware, in grams."""
    printed = 0.0
    for name, part in d['parts'].items():
        v = grid_volume_mm3(part)
        qty = 2 if name in ('rt_grip_pad',) else 1
        dens = 1.2e-3 if name == 'rt_grip_pad' else PETG_DENSITY * PRINT_FILL
        printed += qty * v * dens
    hardware = (SG90_MASS_G                # servo + lead
                + 7.0)                     # M3 mount/lid screws, tab screws
    return printed, hardware


if __name__ == '__main__':
    d = design()
    st = d['st']
    print(f"opening 0..{2 * st['travel']:.0f} mm over {st['rot_deg']:.0f} deg "
          f"of servo swing, extent {st['extent']:.0f} mm beyond the TCP")
    print(f"grip ~{st['f_jaw']:.1f} N per jaw working "
          f"({st['f_jaw_stall']:.1f} N at stall); NOT self-locking — "
          f"keep the servo powered while gripping")
    printed, hw = mass_estimate(d)
    print(f"mass estimate: printed ~{printed:.0f} g + hardware ~{hw:.0f} g "
          f"= ~{printed + hw:.0f} g")
    print(f"robot.yaml updates required: collision.gripper_extent_mm -> "
          f"{math.ceil(st['extent'] / 5) * 5}, masses.gripper_g -> "
          f"{math.ceil((printed + hw) / 10) * 10} (then re-run "
          f"python/validate_cycloid.py)")
    print()
    print(d['checks'].report())
    fails = d['checks'].failures()
    print(f"\n{len(d['checks'].rows)} checks, {len(fails)} failed")
    raise SystemExit(1 if fails else 0)
