"""RobotTwin — cycloidal gearbox generator for Autodesk Fusion (v2, face-mounted).

Generates two single-stage cycloidal gearbox cartridges — 15:1 and 20:1 —
driven entirely by engineering/gearboxes/gear_parameters.yaml, and exports
them per part to engineering/gearboxes/15_1/ and 20_1/:

    rt_cyc<N>_housing  — motor plate + grooved ring (takes Zp Ø6 x 25 steel
                         ring dowels) + Ø76 front mounting flange; bolts
                         face-first to the linkage ear disc (6 x M3 into its
                         heat-set inserts on the Ø66 bolt circle), NEMA 17
                         hangs on the back plate
    rt_cyc<N>_disc     — cycloid disc (x2 per gearbox, cam lobes 180° apart)
    rt_cyc<N>_cam      — eccentric input cam on the motor's 5 mm D-shaft
    rt_cyc<N>_output   — output flange: six Ø6 x 25 steel dowel pins pressed
                         into blind holes reach back through the discs; the
                         hub pinch-clamps the 8 mm joint shaft and its Ø13
                         boss bears on the inboard 608 inner race

Architecture (fixed ring, Zp = Zc + 1 pins, ratio = Zc with reversal): the
motor spins the eccentric cam; two 6802 bearings let the discs wobble on it;
disc lobes walk around the stationary ring pins; the disc's slow rotation
passes through the output holes (Ø = pin + 2e + clearance) to the steel
output pins. Two discs 180° apart balance the eccentric mass and share load.

Hardware assumptions (from the yaml `hardware:` section):
  * every pin is the same Ø6 x 25 mm steel dowel — no printed pins anywhere:
      - ring pins: pressed into blind holes in the back plate and wrapped
        past their equator by full-length wall grooves (also the insertion
        channels, open at the front face); mesh load pushes them into the
        wrap. Ø6 pins force the ring circle to R = 28 (yaml) and the pin
        pattern is clocked so the plate press holes clear the NEMA screws.
      - output pins: pressed ~11.7 mm into the flange — the 25 mm length is
        what sets the Ø62 x 38.4 body (the flange plate absorbs every
        millimetre the discs don't use)
  * main shaft: Ø8 in 608-2RS bearings + shaft collars, all owned by the
    linkage clevis; the hub grips it with a split pinch (tangential M3 +
    captured nut, tightened through an access tunnel in the housing wall)
  * mount: Ø66 bolt circle, 6 x M3 into heat-set inserts in the ear disc
    (cut by linkage_geometry.cut_gearbox_mount). Snug Ø3.2 flange holes make
    the screws locate the housing; the body necks to Ø62/Ø59 so the socket
    heads seat and a hex key passes the bolt circle axially.

The disc profile is generated by simulated hobbing: a cylinder of the ring
pin radius (+ print clearance) is boolean-subtracted along the pin-center
trochoid seen from the disc frame, which yields the exact conjugate envelope
to the sampling resolution. Profile math is validated by
python/validate_cycloid.py, which reads the same yaml.

Z axis = gearbox axis; z = 0 is the back plate face the NEMA 17 bolts to;
z = BODY_L is the front flange face that seats on the linkage ear disc, where
the output boss meets the 608 inner race.

Run from Fusion: UTILITIES > ADD-INS > Scripts and Add-Ins > "+" > select this
folder > Run. Direct modeling, no timeline: edit the yaml and re-run. The
hobbing cuts take a minute or two — Fusion is not hung.

Run from a shell (no Fusion) for a dry run of the parameters and the derived
stack:  python cycloidal_gearbox.py
"""

import math
import os
import re
import traceback

try:
    import adsk.core
    import adsk.fusion
    IN_FUSION = True
except ImportError:
    IN_FUSION = False

# ---------------------------------------------------------------------------
# Standard purchased hardware and print constants (mm). Everything specific
# to THIS gearbox design lives in gear_parameters.yaml, not here.
# ---------------------------------------------------------------------------

# NEMA 17 (17HS4401), mounted directly on the housing back plate
NEMA_HOLE_SPACING = 31.0
NEMA_PILOT_D = 22.5             # pilot boss + clearance
NEMA_PILOT_H = 2.2              # recess depth (boss is 2.0)
NEMA_BORE_D = 14.0              # shaft + boss shoulder clearance through the plate
MOTOR_BORE_D = 5.2              # cam D-bore on the 5 mm shaft
MOTOR_FLAT_X = 2.05
NEMA_SHAFT_LEN_MAX = 25.0       # above the mounting face (measured 23.5)

# 6802-2RS (15 x 24 x 5), one per disc, on the eccentric cam journals
ECC_BRG_BORE = 15.0
CAM_JOURNAL_D = ECC_BRG_BORE + 0.05     # light press after printing

# M3 fasteners
M3_CLEAR_D = 3.4
M3_CB_D = 6.3                   # socket-head counterbore, kept tight: the
                                # ring-pin press holes pass close by at R 28
M3_CB_FLOOR = 1.5               # web left under the motor screw heads
M3_HEAD_D = 5.5
M3_HEAD_H = 3.0
M3_NUT_AF = 5.5                 # across flats
M3_NUT_T = 2.4
HEX_KEY_D = 2.5                 # 2.5 mm key driving the mount screws axially

PROFILE_CLEAR = 0.15            # radial print clearance hobbed into the disc
HOB_STEPS_PER_LOBE = 32         # cutter positions per lobe (envelope err < 0.01)
GAP = 0.5                       # default axial running gap
MIN_WALL = 1.6                  # printable-wall floor (4 perimeters at 0.4 mm)
BUILD_VOLUME = 180.0            # Bambu Lab A1 Mini


# ---------------------------------------------------------------------------
# Parameters — engineering/gearboxes/gear_parameters.yaml is the only source.
# Minimal two-level 'Section: / key: number' parser (Fusion has no PyYAML).
# ---------------------------------------------------------------------------

def yaml_path():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.abspath(os.path.join(
        here, '..', '..', 'gearboxes', 'gear_parameters.yaml'))


def load_params():
    """Returns ({ratio: {key: value}}, {hardware key: value})."""
    with open(yaml_path(), 'r', encoding='utf-8') as f:
        lines = f.read().splitlines()
    data, section = {}, None
    for ln in lines:
        ln = ln.split('#', 1)[0].rstrip()
        if not ln.strip():
            continue
        m = re.match(r'^(\S[^:]*):\s*$', ln)
        if m:
            section = m.group(1)
            data[section] = {}
            continue
        m = re.match(r'^\s+([A-Za-z_]\w*)\s*:\s*(-?[0-9.]+)\s*$', ln)
        if m and section is not None:
            data[section][m.group(1)] = float(m.group(2))
    gears = {}
    for name, vals in data.items():
        m = re.match(r'^(\d+)-1_Gear$', name)
        if m:
            gears[int(m.group(1))] = vals
    hw = data.get('hardware', {})
    if not gears or not hw:
        raise ValueError(f'no gear/hardware sections parsed from {yaml_path()}')
    return gears, hw


# ---------------------------------------------------------------------------
# Derived geometry. One Gearbox object per ratio; everything below is
# computed from the yaml, then self-checked analytically.
# ---------------------------------------------------------------------------

class Checks:
    """Named analytic clearance checks; all must be >= their minimum."""

    def __init__(self):
        self.rows = []              # (label, clearance, minimum)

    def ck(self, label, clearance, minimum):
        self.rows.append((label, clearance, minimum))

    def failures(self):
        return [r for r in self.rows if r[1] < r[2] - 1e-6]

    def report(self):
        lines = []
        for label, c, m in sorted(self.rows, key=lambda r: r[1] - r[2]):
            flag = 'FAIL' if c < m - 1e-6 else 'ok  '
            lines.append(f'{flag} {c:7.2f} >= {m:5.2f}  {label}')
        return '\n'.join(lines)


class Gearbox:
    """All derived dimensions for one ratio (mm, gearbox-local z)."""

    def __init__(self, ratio, g, hw):
        self.ratio = ratio
        self.zp = int(g['external_pins'])
        self.zc = self.zp - 1
        if self.zc != ratio:
            raise ValueError(f'{ratio}:1 section: external_pins {self.zp} '
                             f'implies ratio {self.zc}')
        self.ecc = g['eccentricity']
        self.disc_t = g['thickness']
        self.pin_circle_r = g['fixed_ring_diameter'] / 2.0
        self.ring_pin_d = g['external_pin_diamter']
        self.out_pin_d = g['output_pin_diamter']
        self.out_pin_n = int(g['output_pins'])
        self.disc_bore_d = g['camshaft_hole']
        self.yaml_tip_d = g.get('output_disk_diameter')

        # disc profile (hobbed): cutter = ring pin + print clearance
        self.cutter_d = self.ring_pin_d + 2 * PROFILE_CLEAR
        self.tip_r = self.pin_circle_r + self.ecc - self.cutter_d / 2
        self.root_r = self.pin_circle_r - self.ecc - self.cutter_d / 2
        self.reach_r = self.tip_r + self.ecc     # from the housing axis

        # hardware interface
        self.out_pin_len = hw['output_pin_length']
        self.out_pin_bcd = hw['output_pin_bcd']
        self.pin_hole_d = self.out_pin_d - hw['output_pin_press_fit']
        self.out_hole_d = (self.out_pin_d + 2 * self.ecc
                           + hw['output_hole_clearance'])
        self.ring_pin_len = hw['external_pin_length']
        self.ring_hole_d = self.ring_pin_d - hw['external_pin_press_fit']
        self.groove_d = self.ring_pin_d + hw['ring_groove_clearance']
        self.shaft_bore_d = hw['shaft_diameter'] + hw['shaft_bore_clearance']
        self.mount_bcd = hw['mount_bolt_circle']
        self.mount_n = int(hw['mount_bolt_count'])
        self.mount_hole_d = hw['mount_hole_diameter']
        self.flange_d = hw['mount_flange_diameter']
        self.flange_t = hw['mount_flange_thickness']

        # radial envelope: socket heads seat and the hex key passes the bolt
        # circle axially, so the body necks below the Ø66 BCD
        self.body_d = self.mount_bcd - HEX_KEY_D - 1.5          # 62
        self.collar_d = self.mount_bcd - M3_HEAD_D - 1.5        # 59
        self.ring_id = 2 * self.reach_r + 1.8                   # wobble room
        self.collar_id = self.out_pin_bcd + self.out_pin_d + 8.0    # 50
        self.fp_d = self.out_pin_bcd + self.out_pin_d + 4.0     # flange plate 46
        self.hub_d = 22.0
        self.boss_d = 13.0      # bears on the 608 inner race only

        # axial stack, back plate face -> mounting face
        self.plate_t = 5.0
        self.ring_pin_z0 = 0.5                       # blind-hole floor
        self.ring_pin_z1 = self.ring_pin_z0 + self.ring_pin_len
        self.disc_a_z0 = self.plate_t + GAP
        self.disc_a_z1 = self.disc_a_z0 + self.disc_t
        self.disc_b_z0 = self.disc_a_z1 + GAP
        self.disc_b_z1 = self.disc_b_z0 + self.disc_t
        self.ring_z1 = self.disc_b_z1 + GAP
        self.out_pin_z0 = self.disc_a_z0 + 0.2
        self.out_pin_z1 = self.out_pin_z0 + self.out_pin_len
        self.fp_z0 = self.disc_b_z1 + 1.0            # flange plate bottom
        self.pin_hole_top = self.out_pin_z1 + 0.2    # blind-hole ceiling
        self.fp_z1 = self.pin_hole_top + 0.5         # web over the pins
        self.pocket_top = NEMA_SHAFT_LEN_MAX + 1.0   # motor-shaft-tip room
        self.bore_floor = self.pocket_top + 2.0      # shaft depth stop
        self.cam_z0 = self.disc_a_z0 - 0.2
        self.cam_mid = self.disc_b_z0
        self.cam_z1 = self.ring_z1 - 0.2

        # hub pinch clamp: slit closed by a tangential M3 + captured nut,
        # reached through a Ø6.5 tunnel in the collar/flange wall. The nut
        # window (M3_NUT_AF + 0.7 tall) sits just above the flange plate and
        # sets the minimum hub length; the body is as long as the deeper of
        # the shaft-engagement and nut-window requirements demands.
        self.slit_z0 = self.fp_z1 + 1.0
        self.slit_half = 0.75
        self.pinch_x = 7.0                           # bolt chord offset
        self.pinch_z = self.fp_z1 + 0.2 + M3_NUT_AF / 2 + 0.35
        self.tunnel_d = 6.5
        hub_top_needed = self.pinch_z + M3_NUT_AF / 2 + 0.45
        self.body_l = max(self.bore_floor + hw['shaft_engagement'],
                          hub_top_needed + 0.5)
        self.flange_z0 = self.body_l - self.flange_t
        self.body_top = self.flange_z0 - M3_HEAD_H   # neck for the head seats
        self.hub_z1 = self.body_l - 0.5              # then the Ø13 boss

        self.ring_clock_deg, self._ring_screw_dist = self._ring_clock()
        self.checks = self._check()

    def _ring_clock(self):
        """Clock the ring-pin pattern to maximize the distance between the
        plate's press holes (at R on the pin circle) and the four NEMA screw
        counterbores — both live in the back plate. Returns (deg, min mm)."""
        r_s = NEMA_HOLE_SPACING / 2 * math.sqrt(2)
        pitch = 360.0 / self.zp
        best_c, best_d = 0.0, -1.0
        steps = int(pitch / 0.05)
        for i in range(steps):
            c = i * 0.05
            d = min(math.hypot(
                self.pin_circle_r * math.cos(math.radians(c + j * pitch))
                - r_s * math.cos(math.radians(s)),
                self.pin_circle_r * math.sin(math.radians(c + j * pitch))
                - r_s * math.sin(math.radians(s)))
                for j in range(self.zp) for s in (45, 135, 225, 315))
            if d > best_d:
                best_d, best_c = d, c
        return best_c, best_d

    def _check(self):
        c = Checks()
        ck = c.ck
        # mesh + disc
        lam = self.ecc * self.zp / self.pin_circle_r
        ck('trochoid coefficient below 0.8 (undercut guard)', 0.8 - lam, 0.0)
        ck('radial mesh engagement 2e', 2 * self.ecc, 1.2)
        ck('disc wobble clearance to ring bore',
           self.ring_id / 2 - self.reach_r, 0.75)
        ck('ring wall (groove web) radial depth',
           (self.body_d - self.ring_id) / 2, 2.4)
        web = (2 * self.pin_circle_r * math.sin(math.pi / self.zp)
               - self.groove_d)
        ck('web between ring-pin grooves', web, MIN_WALL)

        def groove_opening(at_r):
            half = (self.groove_d / 2) ** 2 - (at_r - self.pin_circle_r) ** 2
            return 2 * math.sqrt(half) if half > 0 else 0.0
        ck('groove wrap captures the pins (body)',
           self.ring_pin_d - groove_opening(self.body_d / 2), 3.0)
        ck('groove wrap captures the pins (collar)',
           self.ring_pin_d - groove_opening(self.collar_d / 2), 0.5)
        ck('ring-pin press holes clear the NEMA counterbores',
           self._ring_screw_dist - (M3_CB_D + self.ring_hole_d) / 2, 0.0)
        ck('ring pins outlast disc B',
           self.ring_pin_z1 - self.disc_b_z1, 0.5)
        ck('disc output-hole wall to bearing bore',
           self.out_pin_bcd / 2 - self.out_hole_d / 2 - self.disc_bore_d / 2,
           MIN_WALL)
        ck('disc output-hole wall to profile root',
           self.root_r - self.out_pin_bcd / 2 - self.out_hole_d / 2, MIN_WALL)
        if self.yaml_tip_d is not None:
            nominal_tip = 2 * (self.pin_circle_r + self.ecc
                               - self.ring_pin_d / 2)
            ck('yaml output_disk_diameter matches derived tip',
               0.5 - abs(self.yaml_tip_d - nominal_tip), 0.0)
        # mount interface
        ck('socket heads clear the collar',
           (self.mount_bcd - M3_HEAD_D) / 2 - self.collar_d / 2, 0.5)
        ck('hex key clears the body',
           (self.mount_bcd - HEX_KEY_D) / 2 - self.body_d / 2, 0.5)
        ck('mount holes inside the flange',
           (self.flange_d - self.mount_hole_d) / 2 - self.mount_bcd / 2, 1.0)
        # axial stack
        head_top = M3_CB_FLOOR + M3_HEAD_H
        ck('disc A clears the motor screw heads', self.disc_a_z0 - head_top, 0.5)
        ck('output pins clear the motor screw heads',
           self.out_pin_z0 - head_top, 0.5)
        ck('output pins clear the back plate', self.out_pin_z0 - self.plate_t, 0.5)
        ck('flange plate clears disc B', self.fp_z0 - self.disc_b_z1, 0.75)
        ck('flange plate clears the cam', self.fp_z0 - self.cam_z1, 0.5)
        ck('pin embedment in the flange',
           self.pin_hole_top - 0.2 - self.fp_z0, 8.0)
        ck('web between shaft pocket and shaft bore',
           self.bore_floor - self.pocket_top, 1.5)
        ck('motor shaft tip room', self.pocket_top - NEMA_SHAFT_LEN_MAX, 0.5)
        ck('shaft engagement in the hub', self.body_l - self.bore_floor, 8.0)
        ck('flange ring above the plate', self.flange_z0 - self.fp_z1, 1.0)
        ck('ring pins below the pinch tunnel',
           self.pinch_z - self.tunnel_d / 2 - self.ring_pin_z1, 0.5)
        ck('pinch tunnel below the mounting face',
           self.body_l - (self.pinch_z + self.tunnel_d / 2), 0.2)
        ck('pinch bolt above the slit root', self.pinch_z - self.slit_z0, 1.5)
        # pinch hardware walls
        ck('pinch bolt hole wall to shaft bore',
           self.pinch_x - M3_CLEAR_D / 2 - self.shaft_bore_d / 2, 1.0)
        ck('nut pocket below the boss',
           self.hub_z1 - (self.pinch_z + M3_NUT_AF / 2 + 0.35), 0.1)
        ck('nut pocket above the flange plate',
           self.pinch_z - M3_NUT_AF / 2 - 0.35 - self.fp_z1, 0.2)
        ck('nut pocket wall to shaft bore',
           math.hypot(self.pinch_x - M3_NUT_AF / 2 - 0.1, 3.0)
           - self.shaft_bore_d / 2, 0.8)
        # radial interior
        ck('output pins clear the collar bore',
           self.collar_id / 2 - (self.out_pin_bcd + self.out_pin_d) / 2, 1.0)
        ck('output pins clear the ring pins',
           self.pin_circle_r - self.ring_pin_d / 2
           - (self.out_pin_bcd + self.out_pin_d) / 2, 1.0)
        ck('flange plate clears the ring pins',
           self.pin_circle_r - self.ring_pin_d / 2 - self.fp_d / 2, 1.0)
        ck('mount holes clear the grooves',
           (self.mount_bcd - self.mount_hole_d) / 2
           - (self.pin_circle_r + self.groove_d / 2), 0.2)
        ck('flange plate spins inside the collar',
           (self.collar_id - self.fp_d) / 2, 1.0)
        ck('flange plate holds the pin holes',
           (self.fp_d - self.pin_hole_d) / 2 - self.out_pin_bcd / 2, MIN_WALL)
        ck('boss wall around the shaft bore',
           (self.boss_d - self.shaft_bore_d) / 2, 1.5)
        ck('fits the build volume',
           BUILD_VOLUME - max(self.flange_d, self.body_l), 5.0)
        return c


# ---------------------------------------------------------------------------
# Temporary-BRep helpers (same pattern as robot_linkages.py)
# ---------------------------------------------------------------------------

def _p(x, y, z):
    return adsk.core.Point3D.create(x / 10.0, y / 10.0, z / 10.0)


class Builder:
    """Accumulates one solid body from primitive unions and subtractions."""

    def __init__(self):
        self.tbm = adsk.fusion.TemporaryBRepManager.get()
        self.body = None

    def add(self, tool):
        if self.body is None:
            self.body = tool
        else:
            self.tbm.booleanOperation(self.body, tool,
                                      adsk.fusion.BooleanTypes.UnionBooleanType)

    def cut(self, tool):
        assert self.body is not None, 'cut before any add'
        self.tbm.booleanOperation(self.body, tool,
                                  adsk.fusion.BooleanTypes.DifferenceBooleanType)

    def cyl(self, p1, p2, dia):
        return self.tbm.createCylinderOrCone(_p(*p1), dia / 20.0, _p(*p2), dia / 20.0)

    def box(self, x0, x1, y0, y1, z0, z1):
        center = _p((x0 + x1) / 2, (y0 + y1) / 2, (z0 + z1) / 2)
        obb = adsk.core.OrientedBoundingBox3D.create(
            center,
            adsk.core.Vector3D.create(1, 0, 0),
            adsk.core.Vector3D.create(0, 1, 0),
            abs(x1 - x0) / 10.0, abs(y1 - y0) / 10.0, abs(z1 - z0) / 10.0)
        return self.tbm.createBox(obb)

    def cut_bolt_circle_z(self, cx, cy, bcd, n, dia, z0, z1, clock_deg=0.0):
        for i in range(n):
            a = math.radians(clock_deg) + 2 * math.pi * i / n
            x = cx + bcd / 2 * math.cos(a)
            y = cy + bcd / 2 * math.sin(a)
            self.cut(self.cyl((x, y, z0), (x, y, z1), dia))


# ---------------------------------------------------------------------------
# The four parts (per ratio). All are modeled in gearbox-local coordinates;
# the disc is modeled at its cam-angle-0 pose (center offset +e in X).
# ---------------------------------------------------------------------------

def build_housing(gb):
    """Back plate (the NEMA 17 bolts to it from behind, pilot boss recessed),
    grooved ring wall, necked collar, and the Ø76 front flange with snug M3
    holes on the Ø66 bolt circle. The Zp ring pins are Ø6 x 25 steel dowels:
    dropped in through the full-length wall grooves (their insertion
    channels, open at the front face — the ear disc caps them once mounted)
    and pressed into blind holes in the plate; each groove wraps its pin past
    the equator, so mesh load pushes the pins INTO the wrap. The grooves
    open as hairline slits on the body OD (the Ø66 BCD leaves no room to
    close them) — cosmetic only. One Ø6.5 tangential tunnel through the wall
    lets a driver reach the output hub's pinch bolt, above the pin tops."""
    b = Builder()
    b.add(b.cyl((0, 0, 0), (0, 0, gb.body_top), gb.body_d))
    b.add(b.cyl((0, 0, gb.body_top), (0, 0, gb.flange_z0), gb.collar_d))
    b.add(b.cyl((0, 0, gb.flange_z0), (0, 0, gb.body_l), gb.flange_d))
    b.cut(b.cyl((0, 0, gb.plate_t), (0, 0, gb.ring_z1), gb.ring_id))
    b.cut(b.cyl((0, 0, gb.ring_z1), (0, 0, gb.body_l + 1), gb.collar_id))
    for j in range(gb.zp):
        a = math.radians(gb.ring_clock_deg) + 2 * math.pi * j / gb.zp
        x = gb.pin_circle_r * math.cos(a)
        y = gb.pin_circle_r * math.sin(a)
        b.cut(b.cyl((x, y, gb.plate_t), (x, y, gb.body_l + 1), gb.groove_d))
        b.cut(b.cyl((x, y, gb.ring_pin_z0), (x, y, gb.plate_t + 0.1),
                    gb.ring_hole_d))
    # motor interface: pilot recess from the back, shaft bore, screws from
    # inside into the motor's own threads (heads sunk below the plate top)
    b.cut(b.cyl((0, 0, -1), (0, 0, NEMA_PILOT_H), NEMA_PILOT_D))
    b.cut(b.cyl((0, 0, -1), (0, 0, gb.plate_t + 0.1), NEMA_BORE_D))
    h = NEMA_HOLE_SPACING / 2
    for dx, dy in ((h, h), (h, -h), (-h, h), (-h, -h)):
        b.cut(b.cyl((dx, dy, -1), (dx, dy, gb.plate_t + 0.1), M3_CLEAR_D))
        b.cut(b.cyl((dx, dy, M3_CB_FLOOR), (dx, dy, gb.plate_t + 0.1), M3_CB_D))
    # mount holes: snug on M3 so the screws center the housing on the joint
    b.cut_bolt_circle_z(0, 0, gb.mount_bcd, gb.mount_n, gb.mount_hole_d,
                        gb.flange_z0 - 1, gb.body_l + 1)
    # pinch-bolt access tunnel, along the bolt chord (+Y side, x = pinch_x);
    # rotate the output until its bolt lines up, then drive through here
    b.cut(b.cyl((gb.pinch_x, gb.hub_d / 2 + 1, gb.pinch_z),
                (gb.pinch_x, gb.flange_d / 2 + 2, gb.pinch_z), gb.tunnel_d))
    return b.body


def build_disc(gb):
    """Cycloid disc at the cam-angle-0 pose (center at +e). Profile by
    simulated hobbing: subtract the pin-radius cutter along the pin-center
    trochoid p(t) = R*u(t) - e*u(Zp*t) seen from the disc frame."""
    e, r = gb.ecc, gb.pin_circle_r
    b = Builder()
    b.add(b.cyl((e, 0, gb.disc_a_z0), (e, 0, gb.disc_a_z1), 2 * gb.tip_r))
    n = HOB_STEPS_PER_LOBE * gb.zc
    for k in range(n):
        t = 2 * math.pi * k / n
        x = e + r * math.cos(t) - e * math.cos(gb.zp * t)
        y = r * math.sin(t) - e * math.sin(gb.zp * t)
        b.cut(b.cyl((x, y, gb.disc_a_z0 - 0.1), (x, y, gb.disc_a_z1 + 0.1),
                    gb.cutter_d))
    b.cut(b.cyl((e, 0, gb.disc_a_z0 - 1), (e, 0, gb.disc_a_z1 + 1),
                gb.disc_bore_d))
    b.cut_bolt_circle_z(e, 0, gb.out_pin_bcd, gb.out_pin_n, gb.out_hole_d,
                        gb.disc_a_z0 - 1, gb.disc_a_z1 + 1)
    return b.body


def build_cam(gb):
    """Eccentric input cam: 5 mm D-bore, two journals 180° apart for the
    6802 bearings (they overlap 0.5 mm axially so the body is one solid).
    Identical journals + identical discs = balanced eccentric masses."""
    e = gb.ecc
    b = Builder()
    b.add(b.cyl((e, 0, gb.cam_z0), (e, 0, gb.cam_mid), CAM_JOURNAL_D))
    b.add(b.cyl((-e, 0, gb.cam_mid - 0.5), (-e, 0, gb.cam_z1), CAM_JOURNAL_D))
    bore = b.cyl((0, 0, gb.cam_z0 - 1), (0, 0, gb.cam_z1 + 1), MOTOR_BORE_D)
    flat = b.box(MOTOR_FLAT_X, MOTOR_BORE_D, -MOTOR_BORE_D, MOTOR_BORE_D,
                 gb.cam_z0 - 1, gb.cam_z1 + 1)
    b.tbm.booleanOperation(bore, flat,
                           adsk.fusion.BooleanTypes.DifferenceBooleanType)
    b.cut(bore)
    return b.body


def build_output(gb):
    """Output flange: six blind press-fit holes take the Ø6 x 25 steel dowel
    pins, which reach back through both discs. The hub's blind bore seats the
    8 mm joint shaft (floor = depth stop, above the motor shaft's pocket) and
    is closed onto it by a split pinch: tangential M3 through the hub,
    captured nut slid in through a side window before the bolt goes in. The
    Ø13 boss bears on the inboard 608 inner race, flush with the flange
    face — it replaces the inboard shaft collar (the outboard collar stays
    on the far clevis ear)."""
    b = Builder()
    b.add(b.cyl((0, 0, gb.fp_z0), (0, 0, gb.fp_z1), gb.fp_d))
    b.add(b.cyl((0, 0, gb.fp_z1), (0, 0, gb.hub_z1), gb.hub_d))
    b.add(b.cyl((0, 0, gb.hub_z1), (0, 0, gb.body_l), gb.boss_d))
    b.cut_bolt_circle_z(0, 0, gb.out_pin_bcd, gb.out_pin_n, gb.pin_hole_d,
                        gb.fp_z0 - 1, gb.pin_hole_top)
    b.cut(b.cyl((0, 0, gb.fp_z0 - 1), (0, 0, gb.pocket_top),
                MOTOR_BORE_D + 3.4))            # motor shaft tip spins here
    b.cut(b.cyl((0, 0, gb.bore_floor), (0, 0, gb.body_l + 1), gb.shaft_bore_d))
    # pinch: slit through +X (flexes about the x<2 hinge), bolt along Y
    b.cut(b.box(2.0, gb.hub_d / 2 + 1, -gb.slit_half, gb.slit_half,
                gb.slit_z0, gb.body_l + 0.5))
    px, pz = gb.pinch_x, gb.pinch_z
    b.cut(b.cyl((px, -gb.hub_d / 2 - 1, pz), (px, gb.hub_d / 2 + 1, pz),
                M3_CLEAR_D))
    b.cut(b.cyl((px, 3.5, pz), (px, gb.hub_d / 2 + 1, pz), 7.0))    # head
    # nut window: breaks out the hub side for insertion; the z walls (across
    # the flats) lock rotation, the bolt itself retains the nut
    b.cut(b.box(px - M3_NUT_AF / 2 - 0.1, gb.hub_d / 2 + 1,
                -M3_NUT_T - 3.2, -3.0,
                pz - M3_NUT_AF / 2 - 0.35, pz + M3_NUT_AF / 2 + 0.35))
    return b.body


def disc_b_matrix(gb, x_off):
    """Occurrence transform mapping the disc-A body to the disc-B pose:
    opposite eccentric (cam at 180°) needs the identical disc clocked half a
    lobe: p -> Rz(-pi/Zc)*(p - (e,0,0)) + (-e,0,dz)."""
    e = gb.ecc
    ang = -math.pi / gb.zc
    m = adsk.core.Matrix3D.create()
    m.setToRotation(ang, adsk.core.Vector3D.create(0, 0, 1),
                    adsk.core.Point3D.create(0, 0, 0))
    tx = -e * math.cos(ang) - e + x_off
    ty = -e * math.sin(ang)
    tz = gb.disc_b_z0 - gb.disc_a_z0
    m.translation = adsk.core.Vector3D.create(tx / 10.0, ty / 10.0, tz / 10.0)
    return m


# ---------------------------------------------------------------------------
# Fusion document assembly + export
# ---------------------------------------------------------------------------

def run(context):  # noqa: ARG001 — Fusion entry point signature
    app = adsk.core.Application.get()
    ui = app.userInterface
    try:
        gears, hw = load_params()
        gearboxes = {r: Gearbox(r, g, hw) for r, g in sorted(gears.items())}
        failures = []
        for gb in gearboxes.values():
            failures += [f'{gb.ratio}:1  {label}: {c:.2f} < {m:.2f}'
                         for label, c, m in gb.checks.failures()]
        if failures:
            ui.messageBox('Derived geometry FAILED self-checks — nothing '
                          'built:\n\n' + '\n'.join(failures),
                          'RobotTwin cycloidal gearbox generator')
            return

        doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)
        design = adsk.fusion.Design.cast(app.activeProduct)
        design.designType = adsk.fusion.DesignTypes.DirectDesignType
        root = design.rootComponent

        script_dir = os.path.dirname(os.path.abspath(__file__))
        eng_dir = os.path.abspath(os.path.join(script_dir, '..', '..'))
        exported, failed = [], []
        mgr = design.exportManager

        def try_export(label, options):
            try:
                mgr.execute(options)
                exported.append(label)
            except Exception:
                failed.append(f'{label}: {traceback.format_exc(limit=1)}')

        for gi, gb in enumerate(gearboxes.values()):
            x_off = gi * 120.0          # place the assemblies side by side
            parts = {
                f'rt_cyc{gb.zc}_housing': build_housing(gb),
                f'rt_cyc{gb.zc}_disc': build_disc(gb),
                f'rt_cyc{gb.zc}_cam': build_cam(gb),
                f'rt_cyc{gb.zc}_output': build_output(gb),
            }
            shift = adsk.core.Matrix3D.create()
            shift.translation = adsk.core.Vector3D.create(x_off / 10.0, 0, 0)

            occurrences = {}
            for name, body in parts.items():
                occ = root.occurrences.addNewComponent(shift)
                occ.component.name = name
                occ.component.bRepBodies.add(body)
                occurrences[name] = occ
            # second disc: same component, opposite eccentric, half a lobe over
            root.occurrences.addExistingComponent(
                occurrences[f'rt_cyc{gb.zc}_disc'].component,
                disc_b_matrix(gb, x_off))

            out_dir = os.path.join(eng_dir, 'gearboxes', f'{gb.zc}_1')
            for name, occ in occurrences.items():
                step_path = os.path.join(out_dir, f'{name}.step')
                try_export(f'{gb.zc}_1/{name}.step',
                           mgr.createSTEPExportOptions(step_path, occ.component))
                stl_path = os.path.join(out_dir, f'{name}.stl')
                opts = mgr.createSTLExportOptions(occ, stl_path)
                opts.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementHigh
                try_export(f'{gb.zc}_1/{name}.stl', opts)

        f3d_path = os.path.join(eng_dir, 'f3d', 'rt-gearboxes_cycloidal.f3d')
        try_export(os.path.basename(f3d_path),
                   mgr.createFusionArchiveExportOptions(f3d_path))

        app.activeViewport.fit()

        first = next(iter(gearboxes.values()))
        lines = [
            'Built cycloidal gearbox cartridges from gear_parameters.yaml: '
            + ', '.join(f'{gb.zc}:1 (Zp={gb.zp}, e={gb.ecc} mm)'
                        for gb in gearboxes.values()),
            f'Envelope: Ø{first.body_d:.0f} x {first.body_l:.0f} mm body '
            f'+ Ø{first.flange_d:.0f} x {first.flange_t:.0f} front flange.',
            '',
            'Exported: ' + (', '.join(exported) if exported else 'none'),
        ]
        if failed:
            lines += ['', 'FAILED exports:'] + failed
        lines += ['', 'Validate profiles with python/validate_cycloid.py.']
        ui.messageBox('\n'.join(lines), 'RobotTwin cycloidal gearbox generator')

    except Exception:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))


# ---------------------------------------------------------------------------
# Dry run (no Fusion): parse the yaml, derive, and report the self-checks.
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    import sys
    gears, hw = load_params()
    any_fail = False
    for ratio, g in sorted(gears.items()):
        gb = Gearbox(ratio, g, hw)
        print(f'\n=== {gb.zc}:1  (Zp={gb.zp}, R={gb.pin_circle_r}, '
              f'e={gb.ecc}, ring dowels Ø{gb.ring_pin_d:.0f} x '
              f'{gb.ring_pin_len:.0f} clocked {gb.ring_clock_deg:.2f} deg) ===')
        print(f'  body Ø{gb.body_d:.1f} x {gb.body_l:.1f}, collar '
              f'Ø{gb.collar_d:.1f}, ring bore Ø{gb.ring_id:.2f}, flange '
              f'Ø{gb.flange_d:.0f} x {gb.flange_t:.0f} '
              f'(holes Ø{gb.mount_hole_d} on Ø{gb.mount_bcd} BCD)')
        print(f'  stack: plate 0..{gb.plate_t}, disc A {gb.disc_a_z0}..'
              f'{gb.disc_a_z1}, disc B {gb.disc_b_z0}..{gb.disc_b_z1}, '
              f'flange plate {gb.fp_z0}..{gb.fp_z1}, hub ..{gb.hub_z1}, '
              f'boss ..{gb.body_l}')
        print(f'  output pins Ø{gb.out_pin_d:.0f} x {gb.out_pin_len:.0f}: '
              f'z {gb.out_pin_z0}..{gb.out_pin_z1} '
              f'(embed {gb.out_pin_z1 - gb.fp_z0:.1f} in the flange); '
              f'disc holes Ø{gb.out_hole_d:.2f}')
        print(f'  shaft bore Ø{gb.shaft_bore_d:.1f}, floor z '
              f'{gb.bore_floor}, engagement '
              f'{gb.body_l - gb.bore_floor:.1f}')
        print(gb.checks.report())
        fails = gb.checks.failures()
        any_fail |= bool(fails)
        print(f'  {len(gb.checks.rows)} checks, {len(fails)} failed')
    if not IN_FUSION:
        print('\n(dry run only — run from Fusion to build and export)')
    sys.exit(1 if any_fail else 0)
