"""Pre-build hook: bake config/*.yaml into a generated C++ header.

The firmware has no filesystem, so the twin's YAML configs are compiled into
the flash image and parsed at boot by the same loaders the native/WASM builds
use — editing a pin is a config edit plus reflash, never a code change.

This replaces ESP-IDF's EMBED_TXTFILES. Declared in a component's CMakeLists
under PlatformIO, that mechanism makes the generated `<file>.S` a component
source living *inside* the build dir; PlatformIO's SCons import then re-prepends
$BUILD_DIR to it and the build dies with a doubled-path "Source ... not found"
error (`.pio/build/esp32dev/.pio/build/esp32dev/robot.yaml.S.o`). PlatformIO's
own `board_build.embed_txtfiles` only generates the `.S` for esp-idf without
linking it, so it's no rescue either. Emitting an ordinary header sidesteps the
embed machinery entirely and is fully cross-platform.

Wired as a `pre:` extra_script in platformio.ini, so it runs before compilation
on every `pio run`; the header is rewritten only when the YAML actually changes,
so incremental builds stay fast.
"""
import os

# C++ symbol -> source YAML (basename in the repo's config/ dir). The symbol
# names must match the externs consumed in src/embedded_configs.cpp.
CONFIGS = (
    ("kRobotYaml", "robot.yaml"),
    ("kFirmwareYaml", "firmware.yaml"),
)

# Raw-string delimiter. The build fails loudly if this ever appears in a YAML.
_DELIM = "RT_EMBED_YAML"
_OPEN = 'R"' + _DELIM + "("
_CLOSE = ")" + _DELIM + '"'


def _read_verbatim(path):
    # newline="" keeps the file's bytes byte-faithful (no CRLF translation), so
    # the parser sees exactly what it sees in the native builds.
    with open(path, "r", encoding="utf-8", newline="") as fp:
        return fp.read()


def _render(config_dir):
    lines = [
        "// AUTO-GENERATED by scripts/gen_embedded_configs.py — do not edit.",
        "// Regenerated from config/*.yaml on every build.",
        "#pragma once",
        "",
    ]
    for symbol, filename in CONFIGS:
        text = _read_verbatim(os.path.join(config_dir, filename))
        if _CLOSE in text:
            raise SystemExit(
                "gen_embedded_configs: %s contains the raw-string delimiter %r; "
                "pick a different _DELIM." % (filename, _CLOSE)
            )
        lines.append(
            "inline constexpr char %s[] = %s%s%s;" % (symbol, _OPEN, text, _CLOSE)
        )
        lines.append("")
    return "\n".join(lines)


def generate(project_dir):
    config_dir = os.path.normpath(os.path.join(project_dir, "..", "config"))
    out_path = os.path.join(project_dir, "src", "embedded_yaml_gen.hpp")
    content = _render(config_dir)

    old = None
    if os.path.isfile(out_path):
        with open(out_path, "r", encoding="utf-8", newline="") as fp:
            old = fp.read()
    if old != content:
        with open(out_path, "w", encoding="utf-8", newline="") as fp:
            fp.write(content)
        print("gen_embedded_configs: wrote %s" % out_path)


# PlatformIO injects `Import`/`env`; a bare `python gen_embedded_configs.py`
# (for local testing) has neither, so fall back to the script's own location.
try:
    Import("env")  # noqa: F821  (SCons builtin, only defined under PlatformIO)
    generate(env["PROJECT_DIR"])  # noqa: F821
except NameError:
    if __name__ == "__main__":
        _here = os.path.dirname(os.path.abspath(__file__))
        generate(os.path.join(_here, ".."))
