"""Pre-build hook: turn the `gripper:` block of config/firmware.yaml into a
constexpr rt::GripperConfig for the Arduino.

The ESP32 bakes the YAML in whole and parses it at boot (see
firmware/scripts/gen_embedded_configs.py). An ATmega328P has 2 KB of RAM and no
YAML reader, so it gets the values resolved at compile time instead. Same source
of truth, same units, two different ways of arriving on the board — which is the
point: a calibration change is still a config edit plus a reflash, never a code
change.

Unit conversions here MUST match parseGripper() in
src/hardware/hardware_config.cpp, because the ESP32 and the Arduino both slew
their own rt::GripperAxis and only land together if they agree on the numbers.
That is: microseconds and millimetres in the YAML, seconds and metres in the
struct.

Wired as a `pre:` extra_script in platformio.ini, so it runs before every build;
the header is rewritten only when the values actually change.
"""
import os
import re

# YAML key -> (C++ field, scale to SI). The order here is the struct's field
# order in src/hardware/gripper_config.hpp.
FIELDS = (
    ("pin", "pin", None),
    ("relay_pin", "relayPin", None),
    ("relay_rx_pin", "relayRxPin", None),
    ("relay_baud", "relayBaud", None),
    ("knob_pin", "knobPin", None),
    ("pwm_hz", "pwmHz", 1.0),
    ("closed_pulse_us", "closedPulse", 1e-6),
    ("open_pulse_us", "openPulse", 1e-6),
    ("max_opening_mm", "maxOpening", 1e-3),
    ("speed_mm_s", "speed", 1e-3),
    ("boot_opening_mm", "bootOpening", 1e-3),
    ("release_after_s", "releaseAfter", 1.0),
)

_ENTRY = re.compile(r"^\s+([a-z_]+)\s*:\s*(\S+)")


def _read_gripper_block(firmware_yaml):
    """Pull the indented key/value pairs under the top-level `gripper:` key."""
    with open(firmware_yaml, "r", encoding="utf-8") as fp:
        lines = fp.read().splitlines()

    values = {}
    inside = False
    for line in lines:
        stripped = line.strip()
        if not inside:
            inside = stripped == "gripper:" and not line.startswith(" ")
            continue
        # The block ends at the next top-level key; blank and comment lines
        # (including the wrapped comments between entries) just carry on.
        if stripped and not line.startswith(" "):
            break
        if not stripped or stripped.startswith("#"):
            continue
        match = _ENTRY.match(line.split("#", 1)[0])
        if match:
            values[match.group(1)] = match.group(2)
    return values


def _render(firmware_yaml):
    values = _read_gripper_block(firmware_yaml)
    missing = [key for key, _, _ in FIELDS if key not in values]
    if missing:
        raise SystemExit(
            "gen_gripper_config: config/firmware.yaml gripper block is missing %s"
            % ", ".join(missing)
        )

    lines = [
        "// AUTO-GENERATED by scripts/gen_gripper_config.py -- do not edit.",
        "// Regenerated from the gripper: block of config/firmware.yaml.",
        "#pragma once",
        "",
        '#include "hardware/gripper_config.hpp"',
        "",
        "namespace rt {",
        "",
        "inline constexpr GripperConfig kGripperConfig = {",
    ]
    for key, field, scale in FIELDS:
        raw = values[key]
        if scale is None:
            rendered = str(int(float(raw)))
        else:
            rendered = repr(float(raw) * scale)
        lines.append("    .%s = %s,  // %s: %s" % (field, rendered, key, raw))
    lines += ["};", "", "}  // namespace rt", ""]
    return "\n".join(lines)


def generate(project_dir):
    repo_root = os.path.normpath(os.path.join(project_dir, "..", ".."))
    firmware_yaml = os.path.join(repo_root, "config", "firmware.yaml")
    out_path = os.path.join(project_dir, "src", "gripper_config_gen.hpp")
    content = _render(firmware_yaml)

    old = None
    if os.path.isfile(out_path):
        with open(out_path, "r", encoding="utf-8") as fp:
            old = fp.read()
    if old != content:
        with open(out_path, "w", encoding="utf-8") as fp:
            fp.write(content)
        print("gen_gripper_config: wrote %s" % out_path)


# PlatformIO injects `Import`/`env`; a bare `python gen_gripper_config.py`
# (for local testing) has neither, so fall back to the script's own location.
try:
    Import("env")  # noqa: F821  (SCons builtin, only defined under PlatformIO)
    generate(env["PROJECT_DIR"])  # noqa: F821
except NameError:
    if __name__ == "__main__":
        _here = os.path.dirname(os.path.abspath(__file__))
        generate(os.path.join(_here, ".."))
